# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

# def options(opt):
#     pass

# def configure(conf):
#     conf.check_nonfatal(header_name='stdint.h', define_name='HAVE_STDINT_H')

def build(bld):
    module = bld.create_ns3_module('smartgrid-lte-testbed', ['internet', 'mobility','lte', 'tap-bridge'])
    module.source = [
        'model/smartgrid-lte-testbed.cc', 
        'model/Testbed-link.cc',
        'helper/smartgrid-lte-testbed-helper.cc',
        ]

    module_test = bld.create_ns3_module_test_library('smartgrid-lte-testbed')
    module_test.source = [
        'test/smartgrid-lte-testbed-test-suite.cc',
        ]

    headers = bld(features='ns3header')
    headers.module = 'smartgrid-lte-testbed'
    headers.source = [
        'model/smartgrid-lte-testbed.h', 
        'model/Testbed-link.h',
        'helper/smartgrid-lte-testbed-helper.h',
        ]

    if bld.env.ENABLE_EXAMPLES:
        bld.recurse('examples')

    # bld.ns3_python_bindings()

